### ISSUE TITLE
0.13.0-rc7 -> yaml: line NNN: could not find expected ':'

### ISSUE THREAD

**Issue by pjmcquade** [Mirantis/launchpad_legacy#42]
Hello, 

Using 0.13.0-rc7.   In the installFlags stanza in the DTR section, I'd like to pass the --dtr-ca option in the cluster.yml file:

```
spec:
  dtr:
    version: 2.8.0
    imageRepo: "docker.io/docker"
    #imageRepo: "docker.io/mirantis"
    replicaConfig: sequential
    installFlags:
      - --dtr-external-url https://dtr.example.com:443
      - --ucp-username=admin
      - --ucp-password=orcaorca
      - --ucp-url ucp.example.com:443
      - --ucp-insecure-tls
      - --replica-http-port 80
      - --replica-https-port 443
      - --dtr-ca="-----BEGIN CERTIFICATE-----
MIIFqjCCA5KgAwIBAgIQGHY3AQwhwJJDjWP4ysZGSjANBgkqhkiG9w0BAQUFADBm
(output redacted for brevity)
CFN1biBMa"
      - --debug
```

However, when I run this, I see:

```
[root@hostnamedocker_install]# ./launchpad-linux-x64 --debug --disable-telemetry apply --config cluster.yml
DEBU[0000] analytics disabled, not tracking event 'Cluster Apply Started'
DEBU[0000] opened config file from /root/docker_install/cluster.yml
DEBU[0000] analytics disabled, not tracking event 'Cluster Apply Failed'
FATA[0002] yaml: line 33: could not find expected ':'
```

Thoughts?

**Comment by pjmcquade** [comment]
if I changed the --dtr-ca=to $( cat /path/to/ca.pem) it works, but I was curious as to how it can be passed in the cluster.yml file

**Comment by kke** [comment]
That is not valid YAML.

The correct multi-line syntax that keeps linefeeds would be:

```yaml
foo:
  bar:
    installFlags:
      - | 
          --dtr-ca="-----BEGIN CERTIFICATE-----
          MIIFqjCCA5KgAwIBAgIQGHY3AQwhwJJDjWP4ysZGSjANBgkqhkiG9w0BAQUFADBm
          (output redacted for brevity)
          CFN1biBMa"
```
