### ISSUE TITLE
launchpad init generates a config with unsupported kind: UCP

### ISSUE THREAD

**Issue by omadjoudj** [Mirantis/launchpad_legacy#45]
**Description of the issue:**
`./launchpad init` generates a config with `kind: UCP` which causes error since only `kind: DockerEnterprise` is supported according to [1], a test also confirms it.

**Affected version:** 
version: 0.14.0
commit: c7d9682

**Test case***
```
./launchpad init > cluster.yaml
./launchpad apply
FATA[0000] Key: 'ClusterConfig.Kind' Error:Field validation for 'Kind' failed on the 'eq' tag 
echo $?
1

```

**Generated config**
```
./launchpad init
apiVersion: launchpad.mirantis.com/v1beta3
kind: UCP
metadata:
  name: my-ucp-cluster
spec:
  hosts:
  - address: 10.0.0.1
    role: manager
    engineConfig: {}
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  - address: 10.0.0.2
    role: worker
    engineConfig: {}
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  - address: 10.0.0.3
    role: dtr
    engineConfig: {}
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  ucp:
    version: 3.3.2
  dtr:
    version: 2.8.2
    imageRepo: ""
    installFlags: []
    replicaConfig: sequential
    metadata: null
  engine:
    version: 19.03.12

```

[1]  https://github.com/Mirantis/launchpad/blob/master/docs/configuration-file.md#kind
