### ISSUE TITLE
Launchpad chokes on Terraform's output (AWS examples)

### ISSUE THREAD

**Issue by cognomaton** [Mirantis/launchpad_legacy#67]
Reference documentation: https://github.com/Mirantis/launchpad/blob/master/examples/terraform/aws/README.md

The example states to run `Launchpad` as follows: `terraform output mke_cluster | launchpad apply --config -`
The problem is that Terraform's output contains `EOT` markers:
```
user@machine:~/launchpad/examples/terraform/aws$ terraform output mke_cluster 
<<EOT
"apiVersion": "launchpad.mirantis.com/mke/v1.1"
"kind": "mke"
"spec":
  "hosts":
[snip]
...
[snip]
EOT
user@machine:~/launchpad/examples/terraform/aws$ 
```
Launchpad does not like the `EOT` markers.

A workaround is:
1. `terraform output mke_cluster | tee launchpad.yaml`
2.  edit `launchpad.yaml` and remove both `EOT` lines
3. `launchpad apply`

**Comment by ankolesnikov** [comment]
1+2 can be done by:
`terraform output mke_cluster | sed '1d;$d' > ./launchpad.yaml`
or
`terraform output -json | yq e -P '.mke_cluster.value' - > ./launchpad.yaml`

**Comment by cognomaton** [comment]
@ankolesnikov , thanks for the shortcuts.

The point is that the documentation is inaccurate at its current state, and thus needs to be updated. _Any_ of the workarounds could be used to update the `README.md`; pick the one you like most.

**Comment by kke** [comment]
I wonder where this problem came from, possibly a new version of Terraform. It used to work fine. 

I found this issue from terraforms tracker: https://discuss.hashicorp.com/t/terraform-outputs-with-heredoc-syntax-leaves-eot-in-file/18584/8 but there's no clear resolution.

The json output would be readable by launchpad (yaml reader can read json), but I don't think it's a good solution.

Maybe `terraform output mke_cluster | grep -v EOT | launchpad apply --config -` would be the simplest. 

Need to investigate the options a little.

**Comment by kke** [comment]
Also the yaml output puts ugly quotes around everything, which would be nice to avoid.

**Comment by kke** [comment]
Maybe use a template? https://www.terraform.io/docs/language/functions/templatefile.html

**Comment by kke** [comment]
Or maybe use a regex replace on yamlencode result 🤔 https://github.com/hashicorp/terraform/issues/23322#issuecomment-716627898

**Comment by kke** [comment]
Appears this was changed in terraform 0.14:

> The yamlencode function returns a string, which is then displayed by terraform output as a heredoc because it has multiple lines. We changed the format of terraform output in 0.14 to make it clearer what type values were, and to allow the output value to be used directly in HCL.

**Comment by kke** [comment]
There's `--raw`:

`terraform output --raw mke_cluster` ==> 

```yaml
"apiVersion": "launchpad.mirantis.com/mke/v1.3"
"kind": "mke"
"spec":
  "hosts":
  - "privateInterface": "ens5"
    "role": "manager"
    "ssh":
      "address": "xx.xx.102.33"
      "keyPath": "./ssh_keys/my-mke-cluster.pem"
      "user": "ubuntu"
  - "privateInterface": "ens5"
    "role": "worker"
    "ssh":
      "address": "xx.xx.62.141"
      "keyPath": "./ssh_keys/my-mke-cluster.pem"
      "user": "ubuntu"
  "mke":
    "adminPassword": "orcaorcaorca"
    "adminUsername": "admin"
    "installFlags":
    - "--default-node-orchestrator=kubernetes"
    - "--san=my-mke-cluster-master-lb-xxxxx.elb.eu-central-1.amazonaws.com"
  "msr": {}
```
