### ISSUE TITLE
FATA failed to initialize swarm: Error response from daemon: advertise address must be a non-zero IP address or network interface (with optional port number)

### ISSUE THREAD

**Issue by tuvshinot** [Mirantis/launchpad_legacy#74]
```
apiVersion: launchpad.mirantis.com/mke/v1.3
kind: mke
metadata:
  name: my-mke
spec:
  mke:
    adminUsername: admin
    adminPassword: passw0rd!
    installFlags:
      - --default-node-orchestrator=kubernetes
      - --pod-cidr 10.0.0.0/16
  hosts:
  - role: manager
    ssh:
      address: 192.168.110.100
      keyPath: ~/.ssh/id_rsa
      user: theuser
    privateInterface: enp0s3
  - role: worker
    ssh:
      address: 192.168.110.101
      keyPath: ~/.ssh/id_rsa
      user: theuser
    privateInterface: enp0s3
```
Failing to initialize swarm. no way to set advertise address when initializing swarm.
_NOTE : above spec from mirantis doc and changed values for my nodes._
